### ISSUE TITLE
APIClient call throws AttributeError: 'module' object has no attribute 'APIClient'

### ISSUE THREAD

**Issue by anantasur** [AlpineNow/python-alpine-api#34]

**Comment by ggao** [comment]
hi, @anantasur 
I would suggest you rename your python file name from alpine.py to alpine_runner.py or something else.
if the file name is alpine.py, the import line **import alpine as AlpineAPI** will just import itself.
the real alpine module is not imported.

**Comment by anantasur** [comment]
Thanks man , new to python issue
